package com.sample
 
import com.sample.DroolsTest.RomanticUI;
import com.sample.DroolsTest.Question;

rule "Init"
    when
        not Question();
    then
        String[] possib = {"My main squeeze","My family"};
        Question n = new Question("WHO ARE YOU WATCHING IT WITH?",possib);
		RomanticUI.setGUI(n);
        insert (n);
        System.out.println("First question!");
end


rule "WHO ARE YOU WATCHING IT WITH? My main squeeze"
	when 
		q : Question( content == "WHO ARE YOU WATCHING IT WITH?", 
			picked_answer == "My main squeeze", act)
	then
		q.setAct(false);
		String[] possib = {"YES","NO"};
		Question n = new Question("DO YOU CARE IF HE ENJOYS IT?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "DO YOU CARE IF HE ENJOYS IT? Yes"
	when 
		q : Question( content == "DO YOU CARE IF HE ENJOYS IT?",
		 	picked_answer == "YES", act )
	then
		q.setAct(false);
		String[] possib = {"I love explosions","Brains & Beauty","Let's stick to the 'com' in 'romcom'"};
		Question n = new Question("ACTION PACKED OR THOUGHT PROVOKING?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "ACTION PACKED OR THOUGHT PROVOKING? I love explosions"
	when 
		q : Question( content == "ACTION PACKED OR THOUGHT PROVOKING?", 
			picked_answer == "I love explosions", act )
	then
		q.setAct(false);
		String[] possib = {"About face","NO"};
		Question n = new Question("MILILTARY FAN?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "MILILTARY FAN? NO"
	when 
		q : Question( content == "MILILTARY FAN?", 
			picked_answer == "NO", act )
	then
		q.setAct(false);
		String[] possib = {"Girls have muscle, too!","Male"};
		Question n = new Question("MALE OR FEMALE LEAD?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "ACTION PACKED OR THOUGHT PROVOKING? Brains & Beauty"
	when 
		q : Question( content == "ACTION PACKED OR THOUGHT PROVOKING?", 
			picked_answer == "Brains & Beauty", act )
	then
		q.setAct(false);
		String[] possib = {"YES","NO"};
		Question n = new Question("STARRING AN IT GIRL?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "STARRING AN IT GIRL? NO"
	when 
		q : Question( content == "STARRING AN IT GIRL?", 
			picked_answer == "NO", act )
	then
		q.setAct(false);
		String[] possib = {"Oui","NO"};
		Question n = new Question("FOREIGN FILM?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "FOREIGN FILM? NO"
	when 
		q : Question( content == "FOREIGN FILM?", 
			picked_answer == "NO", act )
	then
		q.setAct(false);
		String[] possib = {"Not crying... just allergies", "Prefer to laugh"};
		Question n = new Question("TERAR JERKER?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "TERAR JERKER? Prefer to laugh"
	when 
		q : Question( content == "TERAR JERKER?", 
			picked_answer == "Prefer to laugh", act )
	then
		q.setAct(false);
		String[] possib = {"NO", "Yummy"};
		Question n = new Question("DO YOU LIKE BEER?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "DO YOU LIKE BEER? NO"
	when 
		q : Question( content == "DO YOU LIKE BEER?", 
			picked_answer == "NO", act )
	then
		q.setAct(false);
		String[] possib = {"Pass", "Of course!"};
		Question n = new Question("DO YOU LIKE ADAM SANDLER?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "DO YOU LIKE ADAM SANDLER? Pass"
	when 
		q : Question( content == "DO YOU LIKE ADAM SANDLER?", 
			picked_answer == "Pass", act )
	then
		q.setAct(false);
		String[] possib = {"This one time...", "Nice girls never get the guy"};
		Question n = new Question("GOOD OR BAD GIRL?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "DO YOU LIKE ADAM SANDLER? Of course!"
	when 
		q : Question( content == "DO YOU LIKE ADAM SANDLER?", 
			picked_answer == "Of course!", act )
	then
		q.setAct(false);
		String[] possib = {"Classic Adam!", "Let's go new"};
		Question n = new Question("90s or 2000s SANDLER?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "ACTION PACKED OR THOUGHT PROVOKING? Let's stick to the 'com' in 'romcom'"
	when 
		q : Question( content == "ACTION PACKED OR THOUGHT PROVOKING?", 
			picked_answer == "Let's stick to the 'com' in 'romcom'", act )
	then
		q.setAct(false);
		String[] possib = {"Yes, please!","Pass"};
		Question n = new Question("JUDD APATOW FILM?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "JUDD APATOW FILM? Yes, please!"
	when 
		q : Question( content == "JUDD APATOW FILM?", 
			picked_answer == "Yes, please!", act )
	then
		q.setAct(false);
		String[] possib = {"Yes","Nah"};
		Question n = new Question("THINKING OF MARRIAGE?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "THINKING OF MARRIAGE? Nah"
	when 
		q : Question( content == "THINKING OF MARRIAGE?", 
			picked_answer == "Nah", act )
	then
		q.setAct(false);
		String[] possib = {"There's humor in sorrow","I see where this is headed"};
		Question n = new Question("BROKEN UP OR KNOCKED UP?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "JUDD APATOW FILM? Pass"
	when 
		q : Question( content == "JUDD APATOW FILM?", 
			picked_answer == "Pass", act )
	then
		q.setAct(false);
		String[] possib = {"Bromance is the best","Girl power!"};
		Question n = new Question("GUYS ONLY?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "GUYS ONLY? Bromance is the best"
	when 
		q : Question( content == "GUYS ONLY?", 
			picked_answer == "Bromance is the best", act )
	then
		q.setAct(false);
		String[] possib = {"Ya man!","NO"};
		Question n = new Question("DO YOU LIKE FAKE JAMAICAN ACCENTS?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "GUYS ONLY? Girl power!"
	when 
		q : Question( content == "GUYS ONLY?", 
			picked_answer == "Girl power!", act )
	then
		q.setAct(false);
		String[] possib = {"She's smitten!","She may be a little unaware"};
		Question n = new Question("IS THE GIRL IN LOVE?",possib);
		RomanticUI.setGUI(n);
		insert (n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "WHO ARE YOU WATCHING IT WITH? My family"
	when
		q: Question(content == "WHO ARE YOU WATCHING IT WITH?", 
			picked_answer == "My family", act)
	then
		q.setAct(false);
		String[] possib = {"Yes", "No"};
		Question n = new Question("DO YOU LIKE ANIMATION?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "DO YOU LIKE ANIMATION? Yes"
	when
		q: Question(content == "DO YOU LIKE ANIMATION?", picked_answer == "Yes", act)
	then
		q.setAct(false);
		String[] possib = {"What about Burton?", "Pixar", "Disney"};
		Question n = new Question("PIXAR OR DISNEY?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "PIXAR OR DISNEY? Pixar"
	when
		q: Question(content == "PIXAR OR DISNEY?", picked_answer == "Pixar", act)
	then
		q.setAct(false);
		String[] possib = {"Robots", "Humans"};
		Question n = new Question("WITH ROBOTS OR HUMANS?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "PIXAR OR DISNEY? Disney"
	when
		q: Question(content == "PIXAR OR DISNEY?", picked_answer == "Disney", act)
	then
		q.setAct(false);
		String[] possib = {"Fighter", "Lover"};
		Question n = new Question("ARE YOU A LOVER OR A FIGHTER?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "DO YOU LIKE ANIMATION? No"
	when
		q: Question(content == "DO YOU LIKE ANIMATION?", picked_answer == "No", act)
	then
		q.setAct(false);
		String[] possib = {"I wish it was Christmas everyday", "Not really"};
		Question n = new Question("DO THE HOLIDAYS MAKE YOU SWOON?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "DO THE HOLIDAYS MAKE YOU SWOON? I wish it was Christmas everyday"
	when
		q: Question(content == "DO THE HOLIDAYS MAKE YOU SWOON?", 
			picked_answer == "I wish it was Christmas everyday", act)
	then
		q.setAct(false);
		String[] possib = {"Maybe something more modern", "Always love the classics"};
		Question n = new Question("DO YOU LIKE BLACK & WHITE FILMS?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "DO YOU LIKE BLACK & WHITE FILMS? Maybe something more modern"
	when
		q: Question(content == "DO YOU LIKE BLACK & WHITE FILMS?", 
			picked_answer == "Maybe something more modern", act)
	then
		q.setAct(false);
		String[] possib = {"More than two and it's hard to follow", "I love complexity"};
		Question n = new Question("HOW MANY LOVE TRIANGLES?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "DO THE HOLIDAYS MAKE YOU SWOON? Not really"
	when
		q: Question(content == "DO THE HOLIDAYS MAKE YOU SWOON?", 
			picked_answer == "Not really", act)
	then
		q.setAct(false);
		String[] possib = {"Something for kiddies, please!", "We have teen in the house"};
		Question n = new Question("LITTLE KIDS OR YOUNG ADULTS?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "LITTLE KIDS OR YOUNG ADULTS? Something for kiddies, please!"
	when
		q: Question(content == "LITTLE KIDS OR YOUNG ADULTS?", 
			picked_answer == "Something for kiddies, please!", act)
	then
		q.setAct(false);
		String[] possib = {"My son wil barf!", "The girls would love that", "Something gender neutral"};
		Question n = new Question("HOW ABOUT A PRINCESS MOVIE?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "LITTLE KIDS OR YOUNG ADULTS? We have teen in the house"
	when
		q: Question(content == "LITTLE KIDS OR YOUNG ADULTS?", 
			picked_answer == "We have teen in the house", act)
	then
		q.setAct(false);
		String[] possib = {"Let's teach them a thing or two", "They rool their eyes at anything \"old\""};
		Question n = new Question("CLASSIC OR 21ST CENTURY STORY?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "CLASSIC OR 21ST CENTURY STORY? Let's teach them a thing or two"
	when
		q: Question(content == "CLASSIC OR 21ST CENTURY STORY?", 
			picked_answer == "Let's teach them a thing or two", act)
	then
		q.setAct(false);
		String[] possib = {"Audrey!", "Katherine!"};
		Question n = new Question("PICK A HEPBURN", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "CLASSIC OR 21ST CENTURY STORY? They rool their eyes at anything \"old\""
	when
		q: Question(content == "CLASSIC OR 21ST CENTURY STORY?", 
			picked_answer == "They rool their eyes at anything \"old\"", act)
	then
		q.setAct(false);
		String[] possib = {"That could work", "Pass"};
		Question n = new Question("WHAT IF IT'S ABOUT HIGH SCHOOL?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "WHAT IF IT'S ABOUT HIGH SCHOOL? Pass"
	when
		q: Question(content == "WHAT IF IT'S ABOUT HIGH SCHOOL?", 
			picked_answer == "Pass", act)
	then
		q.setAct(false);
		String[] possib = {"Definitely no", "We're basically the Von Trapp Family"};
		Question n = new Question("DO THEY LIKE MUSICALS?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "DO THEY LIKE MUSICALS? Definitely no"
	when
		q: Question(content == "DO THEY LIKE MUSICALS?", 
			picked_answer == "Definitely no", act)
	then
		q.setAct(false);
		String[] possib = {"Yes, please", "A kiss isn't going to kill anyone"};
		Question n = new Question("DO YOU WANT AVOID THE AWKWARD LOVE SCENES AT ALL COSTS?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end

rule "DO THEY LIKE MUSICALS? We're basically the Von Trapp Family"
	when
		q: Question(content == "DO THEY LIKE MUSICALS?", 
			picked_answer == "We're basically the Von Trapp Family", act)
	then
		q.setAct(false);
		String[] possib = {"80s", "2000s"};
		Question n = new Question("DO YOU PREFER 80S or 2000S?", possib);
		RomanticUI.setGUI(n);
		insert(n);
		System.out.println(q.content + " ANSWER " + q.picked_answer);
end
	



/**
Here starts the rules with the decision about the film
**/

rule "The Notebook"
	when 
		q : Question( content == "DO YOU CARE IF HE ENJOYS IT?",
		 	picked_answer == "NO", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "The Notebook");
end

rule "Nightmare Before Christmas"
	when
		q: Question(content == "PIXAR OR DISNEY?", picked_answer == "What about Burton?")
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Nightmare Before Christmas");
end

rule "Top Gun"
	when 
		q : Question( content == "MILILTARY FAN?", 
			picked_answer == "About face", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Top Gun");
end

rule "Silver Linings Playbooks"
	when 
		q : Question( content == "STARRING AN IT GIRL?", 
			picked_answer == "YES", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Silver Linings Playbooks");
end

rule "Mr. and Mrs. Smith"
	when 
		q : Question( content == "MALE OR FEMALE LEAD?", 
			picked_answer == "Girls have muscle, too!", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Mr. and Mrs. Smith");
end

rule "Bourne Identity"
	when 
		q : Question( content == "MALE OR FEMALE LEAD?", 
			picked_answer == "Male", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Bourne Identity");
end

rule "Amelie"
	when 
		q : Question( content == "FOREIGN FILM?", 
			picked_answer == "Oui", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Amelie");
end

rule "This is 40"
	when 
		q : Question( content == "THINKING OF MARRIAGE?", 
			picked_answer == "Yes", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "This is 40");
end

rule "Eternal Sunshine of the Spotless Mind"
	when 
		q : Question( content == "TERAR JERKER FILM?", 
			picked_answer == "Not crying... just allergies", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Eternal Sunshine of the Spotless Mind");
end

rule "Forgetting Sarah Marshall"
	when 
		q : Question( content == "BROKEN UP OR KNOCKED UP?", 
			picked_answer == "There's humor in sorrow", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Forgetting Sarah Marshall");
end

rule "Knocked Up"
	when 
		q : Question( content == "BROKEN UP OR KNOCKED UP?", 
			picked_answer == "I see where this is headed", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Knocked Up");
end

rule "I Love You, Man"
	when 
		q : Question( content == "DO YOU LIKE FAKE JAMAICAN ACCENTS?", 
			picked_answer == "Ya man!", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "I Love You, Man");
end

rule "Don Jon"
	when 
		q : Question( content == "DO YOU LIKE FAKE JAMAICAN ACCENTS?", 
			picked_answer == "NO", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Don Jon");
end

rule "Wedding Crashes"
	when 
		q : Question( content == "IS THE GIRL IN LOVE?", 
			picked_answer == "She's smitten!", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Wedding Crashes");
end

rule "There's Something About Mary"
	when 
		q : Question( content == "IS THE GIRL IN LOVE?", 
			picked_answer == "She may be a little unaware", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "There's Something About Mary");
end

rule "American Pie"
	when 
		q : Question( content == "GOOD OR BAD GIRL?", 
			picked_answer == "This one time...", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "American Pie");
end

rule "Girl Next Door"
	when 
		q : Question( content == "GOOD OR BAD GIRL?", 
			picked_answer == "Nice girls never get the guy", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Girl Next Door");
end

rule "Wedding Singer"
	when 
		q : Question( content == "90s or 2000s SANDLER?", 
			picked_answer == "Classic Adam!", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Wedding Singer");
end

rule "Just Go With It"
	when 
		q : Question( content == "90s or 2000s SANDLER?", 
			picked_answer == "Let's go new", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Just Go With It");
end

rule "Drinking Buddies"
	when 
		q : Question( content == "DO YOU LIKE BEER?", 
			picked_answer == "Yummy", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Drinking Buddies");
end

rule "WALL-E"
	when 
		q : Question( content == "WITH ROBOTS OR HUMANS?", 
			picked_answer == "Robots", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "WALL-E");
end

rule "Up"
	when 
		q : Question( content == "WITH ROBOTS OR HUMANS?", 
			picked_answer == "Humans", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Up");
end

rule "Tangled"
	when 
		q : Question( content == "ARE YOU A LOVER OR A FIGHTER?", 
			picked_answer == "Fighter", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Tangled");
end

rule "BeautyAndTheBest"
	when 
		q : Question( content == "ARE YOU A LOVER OR A FIGHTER?", 
			picked_answer == "Lover", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Beauty and the Beast");
end

rule "It's a Wonderful Life"
	when 
		q : Question( content == "DO YOU LIKE BLACK & WHITE FILMS?", 
			picked_answer == "Always love the classics", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "It's a Wonderful Life");
end

rule "The Holiday"
	when 
		q : Question( content == "HOW MANY LOVE TRIANGLES?", 
			picked_answer == "More than two and it's hard to follow", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "The Holiday");
end

rule "Love Actually"
	when 
		q : Question( content == "HOW MANY LOVE TRIANGLES?", 
			picked_answer == "I love complexity", act )
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Love Actually");
end

rule "Moonrise Kingdom"
	when
		q: Question(content == "HOW ABOUT A PRINCESS MOVIE?", 
			picked_answer == "My son wil barf!", act)
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Moonrise Kingdom");
end

rule "Enchanted"
	when
		q: Question(content == "HOW ABOUT A PRINCESS MOVIE?", 
			picked_answer == "The girls would love that", act)
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Enchanted");
end

rule "The Princess Bride"
	when
		q: Question(content == "HOW ABOUT A PRINCESS MOVIE?", 
			picked_answer == "Something gender neutral", act)
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "The Princess Bride");
end

rule "Roman Holiday"
	when
		q: Question(content == "PICK A HEPBURN", 
			picked_answer == "Audrey!", act)
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Roman Holiday");
end

rule "The Philadelphia Story"
	when
		q: Question(content == "PICK A HEPBURN", 
			picked_answer == "Katherine!", act)
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "The Philadelphia Story");
end

rule "10 Things I Hate About you"
	when
		q: Question(content == "WHAT IF IT'S ABOUT HIGH SCHOOL?", 
			picked_answer == "That could work", act)
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "10 Things I Hate About you");
end

rule "Meet the Parents"
	when
		q: Question(content == "DO YOU WANT AVOID THE AWKWARD LOVE SCENES AT ALL COSTS?", 
			picked_answer == "Yes, please", act)
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Meet the Parents");
end

rule "Juno"
	when
		q: Question(content == "DO YOU WANT AVOID THE AWKWARD LOVE SCENES AT ALL COSTS?", 
			picked_answer == "A kiss isn't going to kill anyone", act)
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Juno");
end

rule "Hairspray"
	when
		q: Question(content == "DO YOU PREFER 80S or 2000S?", 
			picked_answer == "80s", act)
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Hairspray");
end

rule "Mamma Mia"
	when
		q: Question(content == "DO YOU PREFER 80S or 2000S?", 
			picked_answer == "2000s", act)
	then
		q.setAct(false);
		RomanticUI.setGUI_answer(q, "Mamma Mia");
end
